### ISSUE TITLE
When running the example "Your First Function" I get an error (Cannot find module '@commands')

### ISSUE THREAD

**Issue by ChildishGiant** [TheMrZZ/sandstone#7] opened 2020-09-22 11:43 UTC
I installed everything using the [installation](https://www.sandstone.dev/docs/start/installation) commands

```
PS F:\code\minecraft\Sandstone Projects> npx ts-node helloworld.ts
Error: Cannot find module '@commands'
Require stack:
- F:\code\minecraft\Sandstone Projects\node_modules\sandstone\_internals\datapack\Datapack.js
- F:\code\minecraft\Sandstone Projects\node_modules\sandstone\_internals\datapack\index.js
- F:\code\minecraft\Sandstone Projects\node_modules\sandstone\_internals\index.js
- F:\code\minecraft\Sandstone Projects\node_modules\sandstone\commands.js
- F:\code\minecraft\Sandstone Projects\helloworld.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._resolveFilename (F:\code\minecraft\Sandstone Projects\node_modules\module-alias\index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (F:\code\minecraft\Sandstone Projects\src\_internals\datapack\Datapack.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
```

**Comment by TheMrZZ** [comment] 2020-09-22 12:24
Thanks for your report. I was able to reproduce this bug in production mode, and managed to fix it. The latest version is now on npm. You can update by running `npm install sandstone@latest` (or `yarn add sandstone@latest` if you're using yarn).

For technical reference, this bug was fixed by following [module-alias documentation on libraries](https://github.com/ilearnio/module-alias#using-within-another-npm-package). I don't know why it worked before, but the problem is now fixed.

**Comment by TheMrZZ** [comment] 2020-09-23 12:44
Having received other feedback telling me it's working now, I'll close this issue. Feel free to reopen it if it still doesn't work on your side!

**Closed by TheMrZZ** 2020-09-23 12:44 UTC
Labels: bug
